#!/usr/bin/env python3
from avro import schema
from util._schema_header import *

class Schema(schema):
    def _get_col_info(self, *keys):
        """
        Gets field info from field[].type.field[key] where key is given as
        an argument.
        To get values from child keys, give multiple keys. For example,
        _get_col_info('name') returns the name of a data array,
        _get_col_info('type', 'type') returns the type because it is nested
        """
        def get_info_rec(col, *keys):
            if len(keys) > 1:
                get_info_rec(col[keys[0]], *keys[1:])
            else:
                return col[keys[0]]
        for field in self.fields:
            parent_name = field.name
            for col in field.type.fields:
                info.append(col.props[key])
        pass

    def get_columns(self,):
        
        pass

    def get_column_types(self,):
        pass
    def load_csv(self,):
        pass
    def load_csvs_folder(self):
        pass
    def _infer_time(self,):
        return True
    infer_time_type = True;
    time_columns = [];
